export enum EngineState {
    COLOR_SELECTION = 'COLOR_SELECTION',
    WAVE_ACTIVE = 'WAVE_ACTIVE',
    WAVE_CLEAR_ANIMATION = 'WAVE_CLEAR_ANIMATION',
    UPGRADE_PHASE = 'UPGRADE_PHASE',
    WAVE_STARTING_ANIMATION = 'WAVE_STARTING_ANIMATION',
    BOSS_FIGHT = 'BOSS_FIGHT',
    ANOMALY_ENCOUNTER = 'ANOMALY_ENCOUNTER',
}
